/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package library_management_system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class IssuedBooks extends javax.swing.JFrame {

    SimpleDateFormat dFormat = new SimpleDateFormat("dd-MM-yyyy");
    Connection connect;
    PreparedStatement pstInsert;
    PreparedStatement pstupDate;
    PreparedStatement pstQueryBook;
    PreparedStatement pstQueryStudent;

    ResultSet rst;
    ResultSet rst1;
    ResultSet rst2;

    /**
     * Creates new form IssuedBooks
     */
    public IssuedBooks() {
        initComponents();
        setIconImage(new ImageIcon("images/bookissue.png").getImage());
        btnissuebook.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txbookid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txstudenid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnissuebook = new javax.swing.JButton();
        btnclose = new javax.swing.JButton();
        txissudate = new com.toedter.calendar.JDateChooser();
        txpossiblereturn = new com.toedter.calendar.JDateChooser();
        btncheckbook = new javax.swing.JButton();
        btncheckstudent = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Library Management System- Issue Books");
        setLocation(new java.awt.Point(450, 150));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Book ID");

        txbookid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Student ID");

        txstudenid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Issue Date");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Possible Return Date");

        btnissuebook.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnissuebook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/isu.png"))); // NOI18N
        btnissuebook.setText("Issue Book");
        btnissuebook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnissuebookActionPerformed(evt);
            }
        });

        btnclose.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/red.png"))); // NOI18N
        btnclose.setText("Close");
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });

        btncheckbook.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btncheckbook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bksearch.png"))); // NOI18N
        btncheckbook.setText("Check Book");
        btncheckbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncheckbookActionPerformed(evt);
            }
        });

        btncheckstudent.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btncheckstudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search.png"))); // NOI18N
        btncheckstudent.setText("Check Student");
        btncheckstudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncheckstudentActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Sylfaen", 3, 18)); // NOI18N
        jLabel6.setText("-------------------------Issued Desire Books------------------------ ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txbookid, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txstudenid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnissuebook)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnclose))
                        .addComponent(txissudate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txpossiblereturn, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btncheckstudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btncheckbook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txbookid, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncheckbook))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txstudenid, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncheckstudent))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txissudate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txpossiblereturn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnissuebook)
                    .addComponent(btnclose))
                .addGap(84, 84, 84))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 460));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/books.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 440, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btncloseActionPerformed

    private void btnissuebookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnissuebookActionPerformed
        String bookid = txbookid.getText();
        String studentid = txstudenid.getText();
        String issuedate = dFormat.format(txissudate.getDate());       
        String possiblereturndate = dFormat.format(txpossiblereturn.getDate());
        String returnbook = "NO";

        try {
            //----code for insert issue books----//
            connect = DriverManager.getConnection("jdbc:mysql://localhost:3306/library", "root", "nh123456");
            pstInsert = connect.prepareStatement("insert into issuedbooks(bookid,studentid,issuedate,possiblereturndate,returnbook) values(?,?,?,?,?)");
            pstInsert.setInt(1, Integer.parseInt(bookid));
            pstInsert.setInt(2, Integer.parseInt(studentid));
            pstInsert.setString(3, issuedate);
            pstInsert.setString(4, possiblereturndate);
            pstInsert.setString(5, returnbook);
            int n = pstInsert.executeUpdate();
            if (n > 0) {
                //System.out.println("ok");
                JOptionPane.showMessageDialog(null, "Successefully Issued");
                btnissuebook.setEnabled(false);
            } else {
                JOptionPane.showMessageDialog(null, "Issued not Successefully");
                //System.out.println("not ok");
            }

            //----code for update booklist status books----//
            pstupDate = connect.prepareStatement("update booklist set status=? where bookid=?");
            pstupDate.setString(1, "Not available");
            pstupDate.setInt(2, Integer.parseInt(bookid));
            pstupDate.executeUpdate();

            //----code for update student bookissuestatus books----//
            pstupDate = connect.prepareStatement("update student set bookissuestatus=? where studentid=?");
            pstupDate.setString(1, "Yes");
            pstupDate.setInt(2, Integer.parseInt(studentid));
            pstupDate.executeUpdate();
            //----code for update returnbooks set status----//
            pstupDate = connect.prepareStatement("update returnbooks set returnstatus=? where bookid=?");
            pstupDate.setString(1, "Not Return");
            pstupDate.setInt(2, Integer.parseInt(bookid));
            pstupDate.executeUpdate();

        } catch (Exception e) {

        }
    }//GEN-LAST:event_btnissuebookActionPerformed

    private void btncheckbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncheckbookActionPerformed
        try {
            connect = DriverManager.getConnection("jdbc:mysql://localhost:3306/library", "root", "nh123456");
            pstQueryBook = connect.prepareStatement("select * from booklist where bookid=?");
            pstQueryBook.setInt(1, Integer.parseInt(txbookid.getText()));
            rst1 = pstQueryBook.executeQuery();
            String status = "";
            btnissuebook.setEnabled(true);
            while (rst1.next()) {
                status = rst1.getString(6);
                if (status.equalsIgnoreCase("Not available")) {
                    btnissuebook.setEnabled(false);
                    JOptionPane.showMessageDialog(null, "Book Already issued");

                    //System.out.println(status);
                    break;

                } else {
                    btnissuebook.setEnabled(true);
                    //System.out.println("somethin wrong");
                }
            }

        } catch (Exception e) {
        }
    }//GEN-LAST:event_btncheckbookActionPerformed

    private void btncheckstudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncheckstudentActionPerformed
        try {

            connect = DriverManager.getConnection("jdbc:mysql://localhost:3306/library", "root", "nh123456");
            pstQueryStudent = connect.prepareStatement("select * from student where studentid=?");
            pstQueryStudent.setInt(1, Integer.parseInt(txstudenid.getText()));
            rst2 = pstQueryStudent.executeQuery();
            String status = "";
            btnissuebook.setEnabled(true);
            while (rst2.next()) {
                status = rst2.getString(5);
                if (status.equalsIgnoreCase("Yes")) {
                    JOptionPane.showMessageDialog(null, "Student Already Takes a Book");
                    btnissuebook.setEnabled(false);
                    //System.out.println(status);
                    break;

                } else {

                    System.out.println("somethin wrong");
                }
            }

        } catch (Exception e) {
        }
    }//GEN-LAST:event_btncheckstudentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IssuedBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IssuedBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IssuedBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IssuedBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IssuedBooks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncheckbook;
    private javax.swing.JButton btncheckstudent;
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btnissuebook;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txbookid;
    private com.toedter.calendar.JDateChooser txissudate;
    private com.toedter.calendar.JDateChooser txpossiblereturn;
    private javax.swing.JTextField txstudenid;
    // End of variables declaration//GEN-END:variables
}
