/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package library_management_system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class ReturnBooks extends javax.swing.JFrame {

    Connection connect;
    PreparedStatement pstInsert;
    PreparedStatement pstupdatebooklist;
    PreparedStatement pstupdatestudent;
    PreparedStatement pstupdateissuebook;
    PreparedStatement pst3;
    ResultSet rst;

    /**
     * Creates new form ReturnBooks
     */
    public ReturnBooks() {
        initComponents();
        setIconImage(new ImageIcon("images/returnicon.png").getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txbookid = new javax.swing.JTextField();
        txstudentid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txissuedate = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txpossiblereturntdate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txreturn = new javax.swing.JTextField();
        btnreturn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnsearch = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Library Management System-Return Book List");
        setLocation(new java.awt.Point(450, 150));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Book ID");
        jLabel1.setPreferredSize(new java.awt.Dimension(158, 25));

        txbookid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txbookid.setPreferredSize(new java.awt.Dimension(158, 25));
        txbookid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txbookidKeyReleased(evt);
            }
        });

        txstudentid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txstudentid.setPreferredSize(new java.awt.Dimension(158, 25));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Student ID");
        jLabel2.setPreferredSize(new java.awt.Dimension(158, 25));

        txissuedate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txissuedate.setPreferredSize(new java.awt.Dimension(158, 25));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Issue Date");
        jLabel3.setPreferredSize(new java.awt.Dimension(158, 25));

        txpossiblereturntdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txpossiblereturntdate.setPreferredSize(new java.awt.Dimension(158, 25));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Possible Return Date");
        jLabel4.setPreferredSize(new java.awt.Dimension(158, 25));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Return Date");
        jLabel5.setPreferredSize(new java.awt.Dimension(158, 25));

        txreturn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txreturn.setPreferredSize(new java.awt.Dimension(158, 25));

        btnreturn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnreturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/retn.png"))); // NOI18N
        btnreturn.setText("Return");
        btnreturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreturnActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/red.png"))); // NOI18N
        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bksearch.png"))); // NOI18N
        btnsearch.setText("Search");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Sylfaen", 3, 18)); // NOI18N
        jLabel6.setText("----------------Feild For Return Books----------------");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txstudentid, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(btnreturn)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton2))
                                        .addComponent(txbookid, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txpossiblereturntdate, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txreturn, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txissuedate, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(34, 34, 34)
                        .addComponent(btnsearch)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(111, 111, 111))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txbookid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txstudentid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txissuedate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btnsearch)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txpossiblereturntdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txreturn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnreturn)
                    .addComponent(jButton2))
                .addGap(62, 62, 62))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 460));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/return.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 390, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnreturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreturnActionPerformed

        try {
            String returnstatus = "Returnd";

            //returndate();
            connect = DriverManager.getConnection("jdbc:mysql://localhost:3306/library", "root", "nh123456");
            pstInsert = connect.prepareStatement("insert into returnbooks(bookid,studentid,issuedate,possiblereturndate,returndate,returnstatus)values(?,?,?,?,?,?)");
            pstInsert.setInt(1, Integer.parseInt(txbookid.getText()));
            pstInsert.setInt(2, Integer.parseInt(txstudentid.getText()));
            pstInsert.setString(3, txissuedate.getText());
            pstInsert.setString(4, txpossiblereturntdate.getText());
            pstInsert.setString(5, txreturn.getText());
            pstInsert.setString(6, returnstatus);
            int n = pstInsert.executeUpdate();
            if (n > 0) {
                JOptionPane.showMessageDialog(null, "Successfully Returnd");
            } else {
                JOptionPane.showMessageDialog(null, "Returnd not Successfully");
            }

            //----code for update booklist ----//
            pstupdatebooklist = connect.prepareStatement("update booklist set status=? where bookid=?");
            pstupdatebooklist.setString(1, "Available");
            pstupdatebooklist.setInt(2, Integer.parseInt(txbookid.getText()));
            pstupdatebooklist.executeUpdate();

            //----code for update student bookissuestatus ----//
            pstupdatestudent = connect.prepareStatement("update student set bookissuestatus=? where studentid=?");
            pstupdatestudent.setString(1, "NO");
            pstupdatestudent.setInt(2, Integer.parseInt(txstudentid.getText()));
            pstupdatestudent.executeUpdate();

            //----code for update issuebooks ----//
            pstupdateissuebook = connect.prepareStatement("update issuedbooks set returnbook=? where bookid=?");
            pstupdateissuebook.setString(1, "Returnd");
            pstupdateissuebook.setInt(2, Integer.parseInt(txbookid.getText()));
            pstupdateissuebook.executeUpdate();

        } catch (Exception e) {
            e.printStackTrace();

        }

    }//GEN-LAST:event_btnreturnActionPerformed

//    public void returndate() {
//        LocalDate today = LocalDate.now();
//        txreturn.setText(String.valueOf(today));
//    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
//try {
//
//            connect = DriverManager.getConnection("jdbc:mysql://localhost:3306/library", "root", "nh123456");
//            pst3 = connect.prepareStatement("select * from issuedbooks where bookid=?");
//            pst3.setInt(1, Integer.parseInt(txbookid.getText()));
//            rst = pst3.executeQuery();
//            
//            if (rst.next()) {
//                txstudentid.setText(String.valueOf(rst.getInt(3)));
//                txissuedate.setText(rst.getString(4));
//                txpossiblereturntdate.setText(rst.getString(5));
//
//            } else {
//                JOptionPane.showMessageDialog(null, "The Book is not issued");
//            }
//        } catch (Exception e) {
//            //e.printStackTrace();
//        }


    }//GEN-LAST:event_btnsearchActionPerformed

    private void txbookidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txbookidKeyReleased

        if (txbookid.getText().equals("")) {
            txbookid.setText(String.valueOf(0));
        }

        try {

            connect = DriverManager.getConnection("jdbc:mysql://localhost:3306/library", "root", "nh123456");
            pst3 = connect.prepareStatement("select * from issuedbooks where bookid=?");
            pst3.setInt(1, Integer.parseInt(txbookid.getText()));
            rst = pst3.executeQuery();

            if (rst.next()) {
                txstudentid.setText(String.valueOf(rst.getInt(3)));
                txissuedate.setText(rst.getString(4));
                txpossiblereturntdate.setText(rst.getString(5));
                txreturn.setText(String.valueOf(LocalDate.now()));

            } else {
                JOptionPane.showMessageDialog(null, "The Book is not issued");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_txbookidKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnBooks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnreturn;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txbookid;
    private javax.swing.JTextField txissuedate;
    private javax.swing.JTextField txpossiblereturntdate;
    private javax.swing.JTextField txreturn;
    private javax.swing.JTextField txstudentid;
    // End of variables declaration//GEN-END:variables
}
